name: test

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
    - name: Dependency scan
      run: |
        cargo install cargo-audit || true
        cargo audit || true
